// Tests for the openapi-typescript output sanitizer. Run with:
//   deno test -A src/openapi-sanitize_test.ts
//
// The pure tests assert the structural rewrite; the final integration test runs
// the real `deno check` to lock in the property that actually matters - that a
// recursive schema no longer fails the whole-program type check (TS2502).

import { assert, assertEquals, assertStringIncludes } from "@std/assert";
import { sanitizeRecursiveSchemaAliases } from "./openapi-sanitize.ts";

/** Wrap a schemas-object body in an otherwise-minimal openapi-typescript file. */
function file(schemasBody: string): string {
  return `/**
 * This file was auto-generated by openapi-typescript.
 */
export interface paths {
    "/x": {
        get: operations["getX"];
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
${schemasBody}
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getX: {
        responses: {
            200: {
                content: {
                    "application/json": components["schemas"]["json"];
                };
            };
        };
    };
}
`;
}

Deno.test("lifts a direct self-referential schema (the arbitrary-JSON pattern)", () => {
  const src = file(
    `        "json": string | number | boolean | {
            [key: string]: components["schemas"]["json"];
        } | components["schemas"]["json"][];`,
  );
  const { text, lifted } = sanitizeRecursiveSchemaAliases(src);

  assertEquals(lifted, 1);
  // The member now points at the lifted alias.
  assertStringIncludes(text, `"json": __anyapi_rec_0;`);
  // A top-level recursive alias was emitted, before the components interface.
  assertStringIncludes(text, "type __anyapi_rec_0 =");
  assert(
    text.indexOf("type __anyapi_rec_0 =") <
      text.indexOf("export interface components"),
    "alias must be hoisted above the components interface",
  );
  // Inside the alias the self-references became the alias name; none of the
  // original indexed-access self-references survive in it.
  const alias = text.slice(
    text.indexOf("type __anyapi_rec_0 ="),
    text.indexOf("export interface components"),
  );
  assertStringIncludes(alias, "__anyapi_rec_0");
  assert(
    !alias.includes(`components["schemas"]["json"]`),
    "self-references inside the alias should be rewritten",
  );
  // External references (here, from operations) still resolve via the member.
  assertStringIncludes(
    text,
    `"application/json": components["schemas"]["json"];`,
  );
});

Deno.test("lifts both schemas in an indirect (eager) $ref cycle", () => {
  const src = file(
    `        A: string | components["schemas"]["B"][];
        B: number | components["schemas"]["A"][];`,
  );
  const { text, lifted } = sanitizeRecursiveSchemaAliases(src);

  assertEquals(lifted, 2);
  assertStringIncludes(text, "A: __anyapi_rec_0;");
  assertStringIncludes(text, "B: __anyapi_rec_1;");
  // The aliases reference each other by name, not by indexed access.
  assertStringIncludes(
    text,
    "type __anyapi_rec_0 = string | __anyapi_rec_1[];",
  );
  assertStringIncludes(
    text,
    "type __anyapi_rec_1 = number | __anyapi_rec_0[];",
  );
});

Deno.test("leaves a property-only cycle untouched (lazy, type-checks as-is)", () => {
  const src = file(
    `        A: {
            b?: components["schemas"]["B"];
        };
        B: {
            a?: components["schemas"]["A"];
        };`,
  );
  const { text, lifted } = sanitizeRecursiveSchemaAliases(src);
  assertEquals(lifted, 0);
  assertEquals(text, src); // byte-for-byte unchanged
});

Deno.test("leaves a self-reference reachable only through an index signature", () => {
  const src = file(
    `        Bag: {
            [key: string]: components["schemas"]["Bag"];
        };`,
  );
  const { lifted, text } = sanitizeRecursiveSchemaAliases(src);
  assertEquals(lifted, 0);
  assertEquals(text, src);
});

Deno.test("no-op when there is no schemas object", () => {
  const src = `export interface components {
    schemas: never;
    responses: never;
}
`;
  const { lifted, text } = sanitizeRecursiveSchemaAliases(src);
  assertEquals(lifted, 0);
  assertEquals(text, src);
});

Deno.test("no-op when there is no components interface", () => {
  const src = `export interface paths {
    "/x": { get: { responses: { 200: { content: never } } } };
}
`;
  const { lifted, text } = sanitizeRecursiveSchemaAliases(src);
  assertEquals(lifted, 0);
  assertEquals(text, src);
});

Deno.test("decodes quoted schema names with special characters", () => {
  const src = file(
    `        "foo-bar.baz": string | components["schemas"]["foo-bar.baz"][];`,
  );
  const { text, lifted } = sanitizeRecursiveSchemaAliases(src);
  assertEquals(lifted, 1);
  assertStringIncludes(text, `"foo-bar.baz": __anyapi_rec_0;`);
  assertStringIncludes(
    text,
    "type __anyapi_rec_0 = string | __anyapi_rec_0[];",
  );
});

Deno.test("does not treat indexed-access text inside a description comment as a reference", () => {
  // A JSDoc mentioning the pattern must not create a phantom self-cycle.
  const src = file(
    `        /** see components["schemas"]["Other"] for details */
        Plain: {
            id?: string;
        };`,
  );
  const { lifted, text } = sanitizeRecursiveSchemaAliases(src);
  assertEquals(lifted, 0);
  assertEquals(text, src);
});

// ---- integration: the sanitized output actually type-checks ----

async function denoCheckPasses(dts: string): Promise<boolean> {
  const dir = await Deno.makeTempDir({ prefix: "anyapi-sanitize-test-" });
  try {
    await Deno.writeTextFile(`${dir}/types.d.ts`, dts);
    await Deno.writeTextFile(
      `${dir}/use.ts`,
      `import type { components } from "./types.d.ts";\n` +
        `const v = null as unknown as components["schemas"]["json"];\n` +
        `console.log(v);\n`,
    );
    const { code } = await new Deno.Command("deno", {
      args: ["check", `${dir}/use.ts`],
      stdout: "null",
      stderr: "null",
    }).output();
    return code === 0;
  } finally {
    await Deno.remove(dir, { recursive: true }).catch(() => {});
  }
}

Deno.test("a recursive schema fails deno check before, and passes after", async () => {
  const bad = file(
    `        "json": string | number | boolean | {
            [key: string]: components["schemas"]["json"];
        } | components["schemas"]["json"][];`,
  );
  assert(!(await denoCheckPasses(bad)), "unsanitized input should fail TS2502");
  const { text } = sanitizeRecursiveSchemaAliases(bad);
  assert(await denoCheckPasses(text), "sanitized output should type-check");
});
